#:schema node_modules/wrangler/config-schema.json

name = "suenyiyang-waline"
main = "src/index.ts"
compatibility_date = "2026-06-10"

[vars]
SITE_NAME = "suenyiyang.com"
SITE_URL = "https://suenyiyang.com"
SECURE_DOMAINS = "suenyiyang.com,waline.suenyiyang.com"

[[routes]]
pattern = "waline.suenyiyang.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "waline-db"
database_id = "7713376b-89b9-434c-83aa-92b946196f3e"
